# Generated by Django 5.2.4 on 2025-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="fine",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
